#
# Makefile for smoopy
#

    CC = gcc
RANLIB = ranlib

INCGCC = $(GCCINC)
ADDINCS = 
AD_C_FLAGS =
ARFLAGS =

#Includes for older gcc compilation
#INCLUDES = -I../include -I../../include -I$(GCCINC) -I/usr/include -nostdinc $(ADDINCS)
#
INCLUDES = -I../include -I../../include -I$(GCCINC) -I/usr/include $(ADDINCS)

#INCLUDES = -I../include -I../../include -I../lib/include $(ADDINCS)

LIBRARY = ../libopt.a

#
# CFLAGS for gcc, add -Wno-unknown-pragmas for egcs or gcc-2.95
CFLAGS = -ansi -c -g -D$(MDEBUG) -D$(SYSTEM) -D$(USAPPEND) $(INCLUDES) -Wall -Wpointer-arith -Wshadow -Wnested-externs $(AD_C_FLAGS)

#
# CFLAGS for SUN cc (ANSI)
# code does not work with SunC due to using adjustable arrays which are 
# a GNU C extension. These must be replaced with dynamic routines to work
# with SunC.
#CFLAGS = -c -g -D$(MDEBUG) -D$(SYSTEM) -D$(USAPPEND) $(INCLUDES) -I/usr/include -Xa $(AD_C_FLAGS) #-xO4

SOURCES = correct_vect.c \
          func.c \
          gdfp_optimize.c \
          init_vec.c \
          swap.c \
          update_h.c \
          update_nn1.c

OBJECTS = $(SOURCES:.c=.o)

.KEEP_STATE:

all: $(LIBRARY)

OBJS: $(OBJECTS)

$(LIBRARY): OBJS FORCE
	rm -f $@
	ar $(ARFLAGS) rc $@  $(OBJECTS)
	$(RANLIB) $@
#	rm -f $(OBJECTS)

depend:
	makedepend -f Makefile.opt -- $(CFLAGS) -- $(SOURCES)

FORCE:

# DO NOT DELETE

correct_vect.o: ../../include/Stdio.h /usr/include/stdio.h
correct_vect.o: /usr/include/features.h /usr/include/stdc-predef.h
correct_vect.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
correct_vect.o: /usr/include/gnu/stubs.h
correct_vect.o: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h
correct_vect.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
correct_vect.o: /usr/include/libio.h /usr/include/_G_config.h
correct_vect.o: /usr/include/wchar.h
correct_vect.o: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h
correct_vect.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
correct_vect.o: /usr/include/stdlib.h /usr/include/bits/waitflags.h
correct_vect.o: /usr/include/bits/waitstatus.h /usr/include/endian.h
correct_vect.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
correct_vect.o: /usr/include/bits/byteswap-16.h /usr/include/sys/types.h
correct_vect.o: /usr/include/time.h /usr/include/sys/select.h
correct_vect.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
correct_vect.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
correct_vect.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
correct_vect.o: /usr/include/bits/stdlib-float.h ../../include/Math.h
correct_vect.o: /usr/include/math.h /usr/include/bits/huge_val.h
correct_vect.o: /usr/include/bits/huge_valf.h /usr/include/bits/huge_vall.h
correct_vect.o: /usr/include/bits/inf.h /usr/include/bits/nan.h
correct_vect.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
correct_vect.o: ../../include/mem_er.h ../include/constraint.h
correct_vect.o: ../../include/file_path.h
func.o: ../../include/Stdio.h /usr/include/stdio.h /usr/include/features.h
func.o: /usr/include/stdc-predef.h /usr/include/sys/cdefs.h
func.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
func.o: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h
func.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
func.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
func.o: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h
func.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
func.o: ../../include/Math.h /usr/include/math.h /usr/include/bits/huge_val.h
func.o: /usr/include/bits/huge_valf.h /usr/include/bits/huge_vall.h
func.o: /usr/include/bits/inf.h /usr/include/bits/nan.h
func.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
func.o: ../../include/bisp.h
gdfp_optimize.o: ../../include/Stdio.h /usr/include/stdio.h
gdfp_optimize.o: /usr/include/features.h /usr/include/stdc-predef.h
gdfp_optimize.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
gdfp_optimize.o: /usr/include/gnu/stubs.h
gdfp_optimize.o: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h
gdfp_optimize.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
gdfp_optimize.o: /usr/include/libio.h /usr/include/_G_config.h
gdfp_optimize.o: /usr/include/wchar.h
gdfp_optimize.o: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h
gdfp_optimize.o: /usr/include/bits/stdio_lim.h
gdfp_optimize.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
gdfp_optimize.o: /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h
gdfp_optimize.o: /usr/include/endian.h /usr/include/bits/endian.h
gdfp_optimize.o: /usr/include/bits/byteswap.h /usr/include/bits/byteswap-16.h
gdfp_optimize.o: /usr/include/sys/types.h /usr/include/time.h
gdfp_optimize.o: /usr/include/sys/select.h /usr/include/bits/select.h
gdfp_optimize.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
gdfp_optimize.o: /usr/include/sys/sysmacros.h
gdfp_optimize.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
gdfp_optimize.o: /usr/include/bits/stdlib-float.h ../../include/Math.h
gdfp_optimize.o: /usr/include/math.h /usr/include/bits/huge_val.h
gdfp_optimize.o: /usr/include/bits/huge_valf.h /usr/include/bits/huge_vall.h
gdfp_optimize.o: /usr/include/bits/inf.h /usr/include/bits/nan.h
gdfp_optimize.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
gdfp_optimize.o: ../include/constraint.h ../../include/file_path.h
init_vec.o: ../../include/Stdio.h /usr/include/stdio.h
init_vec.o: /usr/include/features.h /usr/include/stdc-predef.h
init_vec.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
init_vec.o: /usr/include/gnu/stubs.h
init_vec.o: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h
init_vec.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
init_vec.o: /usr/include/libio.h /usr/include/_G_config.h
init_vec.o: /usr/include/wchar.h
init_vec.o: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h
init_vec.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
swap.o: ../../include/Stdio.h /usr/include/stdio.h /usr/include/features.h
swap.o: /usr/include/stdc-predef.h /usr/include/sys/cdefs.h
swap.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
swap.o: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h
swap.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
swap.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
swap.o: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h
swap.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
update_h.o: ../../include/Stdio.h /usr/include/stdio.h
update_h.o: /usr/include/features.h /usr/include/stdc-predef.h
update_h.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
update_h.o: /usr/include/gnu/stubs.h
update_h.o: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h
update_h.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
update_h.o: /usr/include/libio.h /usr/include/_G_config.h
update_h.o: /usr/include/wchar.h
update_h.o: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h
update_h.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
update_h.o: ../../include/mem_er.h
update_nn1.o: ../../include/Stdio.h /usr/include/stdio.h
update_nn1.o: /usr/include/features.h /usr/include/stdc-predef.h
update_nn1.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
update_nn1.o: /usr/include/gnu/stubs.h
update_nn1.o: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h
update_nn1.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
update_nn1.o: /usr/include/libio.h /usr/include/_G_config.h
update_nn1.o: /usr/include/wchar.h
update_nn1.o: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h
update_nn1.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
update_nn1.o: /usr/include/stdlib.h /usr/include/bits/waitflags.h
update_nn1.o: /usr/include/bits/waitstatus.h /usr/include/endian.h
update_nn1.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
update_nn1.o: /usr/include/bits/byteswap-16.h /usr/include/sys/types.h
update_nn1.o: /usr/include/time.h /usr/include/sys/select.h
update_nn1.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
update_nn1.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
update_nn1.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
update_nn1.o: /usr/include/bits/stdlib-float.h ../../include/mem_er.h
